spring:
   jpa:
      hibernate:
         ddl-auto: update

   datasource:
      url: jdbc:mysql://${DB_SERVER:docker:8306}/training?autoReconnect=true
      username: ${DB_USER:training}
      password: ${DB_PASSWORD:dodol123}

com.senomas:
   http-logger:
      order: 0
      path:
         "/": BASIC
         "/v2/api-docs": OFF
         "/swagger-": OFF
         "/configuration/": OFF
         "/rs/": ALL


logging:
   level:
      '*': DEBUG
      org.hibernate.SQL: DEBUG
      com.senomas: DEBUG


---
spring:
   profiles: dev-db
   jpa:
      hibernate:
         ddl-auto: create-drop

---
spring:
   profiles: dev-mem
   jpa:
      hibernate:
         ddl-auto: create-drop

   datasource:
      url: jdbc:hsqldb:mem:training
      username: sa
      password: 

